# Generated by Django 2.0.7 on 2018-07-09 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinsession',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='checkinsession',
            name='start_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='checkinsession',
            name='status',
            field=models.CharField(choices=[('STARTED', 'Just STARTED'), ('IN_PROGRESS', 'Checking in'), ('CANCELED', 'Canceled'), ('COMPLETED', 'Completed')], default='STARTED', max_length=3),
        ),
        migrations.AlterField(
            model_name='checkinsession',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
    ]
