# Generated by Django 2.0.7 on 2018-07-13 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elists', '0005_auto_20180710_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinsession',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Член ВКС'),
        ),
        migrations.AlterField(
            model_name='checkinsession',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Student', verbose_name='Виборець'),
        ),
    ]
