# Generated by Django 2.0.7 on 2018-07-13 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elists', '0006_auto_20180714_0013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkinsession',
            options={'verbose_name': 'Чек-ін сесія', 'verbose_name_plural': 'Чек-ін сесії'},
        ),
        migrations.AddField(
            model_name='checkinsession',
            name='doc_num',
            field=models.CharField(max_length=8, null=True, verbose_name='Номер документу'),
        ),
        migrations.AddField(
            model_name='checkinsession',
            name='doc_type',
            field=models.IntegerField(choices=[(0, 'Студентський квиток'), (1, 'Залікова книжка'), (2, 'Довідка від деканату')], null=True, verbose_name='Тип документу'),
        ),
        migrations.AlterField(
            model_name='checkinsession',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Персонал'),
        ),
        migrations.AlterField(
            model_name='checkinsession',
            name='status',
            field=models.IntegerField(choices=[(1, 'Відкрита'), (2, 'В процесі'), (-1, 'Відмінена'), (0, 'Завершена')], verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='checkinsession',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Student', verbose_name='Студент'),
        ),
    ]
