# Generated by Django 2.1 on 2018-09-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elists', '0007_auto_20180714_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkinsession',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='checkinsession',
            name='start_time',
        ),
        migrations.AddField(
            model_name='checkinsession',
            name='end_dt',
            field=models.DateTimeField(null=True, verbose_name='Час завершення'),
        ),
        migrations.AddField(
            model_name='checkinsession',
            name='start_dt',
            field=models.DateTimeField(auto_now_add=True, default='2012-12-25', verbose_name='Час початку'),
            preserve_default=False,
        ),
    ]
