# Generated by Django 2.1 on 2018-09-30 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elists', '0008_auto_20180928_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinsession',
            name='num_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Чисельний код'),
        ),
    ]
