# Generated by Django 2.1 on 2018-09-30 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elists', '0009_checkinsession_num_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinsession',
            name='num_code',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Чисельний код'),
        ),
    ]
