export const ICONS = {
  admin: 'fas fa-tools',
  bug: 'fas fa-bug',
  camera: 'fas fa-camera',
  card: 'fas fa-id-card',
  certificate: 'fas fa-certificate',
  check: 'fas fa-check',
  errorIcon: 'fas fa-exclamation-circle',
  gradeBook: 'fas fa-book-open',
  readyIcon: 'fas fa-circle',
  scanningIcon: 'fas fa-video',
  searchingIcon: 'fas fa-search',
  scannedIcon: 'far fa-check-circle',
  studentCard: 'fas fa-address-card',
  language: 'fas fa-language',
  login: 'fas fa-sign-in-alt',
  logout: 'fas fa-sign-out-alt',
  user: 'fas fa-user-circle',
  userCheck: 'fas fa-user-check',
}
