# Generated by Django 2.0.7 on 2018-07-09 13:05

from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StructuralUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Specialty'),
        ),
        migrations.AlterField(
            model_name='student',
            name='structural_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StructuralUnit'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_ticket_number',
            field=models.CharField(max_length=8, validators=[student.models.validate_student_ticket_number]),
        ),
    ]
