# Generated by Django 2.0.7 on 2018-07-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20180709_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('Y1', '1'), ('Y2', '2'), ('Y3', '3'), ('Y4', '4')], max_length=3),
        ),
    ]
