# Generated by Django 2.0.7 on 2018-07-10 16:11

from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20180709_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_ticket_number',
        ),
        migrations.AddField(
            model_name='student',
            name='ticket_number',
            field=models.CharField(default='00000000', max_length=8, validators=[student.models.validate_student_ticket_number], verbose_name='Student ticket number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='student',
            name='educational_degree',
            field=models.IntegerField(choices=[(1, 'Bachelor'), (2, 'Master')], verbose_name='Educational degree'),
        ),
        migrations.AlterField(
            model_name='student',
            name='form_of_study',
            field=models.IntegerField(choices=[(1, 'External'), (2, 'Full-time')], verbose_name='Form of study'),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=100, validators=[student.models.validate_student_full_name], verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.Specialty', verbose_name='Specialty'),
        ),
        migrations.AlterField(
            model_name='student',
            name='structural_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.StructuralUnit', verbose_name='Structural unit (faculty/institute)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Year'),
        ),
    ]
