# Generated by Django 2.0.7 on 2018-07-10 18:03

import django.db.models.deletion
from django.db import migrations, models

import student.models


class Migration(migrations.Migration):
    dependencies = [
        ('student', '0005_auto_20180710_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name': 'Спеціальність', 'verbose_name_plural': 'Спеціальності'},
        ),
        migrations.AlterModelOptions(
            name='structuralunit',
            options={'verbose_name': 'Структурний підрозділ', 'verbose_name_plural': 'Структурні підрозділи'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студенти'},
        ),
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='structuralunit',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(verbose_name='Дата народження'),
        ),
        migrations.AlterField(
            model_name='student',
            name='educational_degree',
            field=models.IntegerField(choices=[(1, 'Бакалавр'), (2, 'Магістр')], verbose_name='Освітній ступінь'),
        ),
        migrations.AlterField(
            model_name='student',
            name='form_of_study',
            field=models.IntegerField(choices=[(1, 'Денна'), (2, 'Заочна')], verbose_name='Форма навчання'),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=100, validators=[student.models.validate_student_full_name],
                                   verbose_name="Призвище Ім'я По-батькові"),
        ),
        migrations.AlterField(
            model_name='student',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.Specialty',
                                    verbose_name='Спеціальність'),
        ),
        migrations.AlterField(
            model_name='student',
            name='structural_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.StructuralUnit',
                                    verbose_name='Структурний підрозділ (факультет/інститут)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='ticket_number',
            field=models.CharField(max_length=8, validators=[student.models.validate_student_ticket_number],
                                   verbose_name='Номер студентського квитка'),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Курс'),
        ),
    ]
