# Generated by Django 2.0.7 on 2018-07-10 18:26

from django.db import migrations, models

import student.models


class Migration(migrations.Migration):
    dependencies = [
        ('student', '0006_auto_20180710_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ticket_number',
            field=models.IntegerField(unique=True, validators=[student.models.validate_student_ticket_number],
                                      verbose_name='Номер студентського квитка'),
        ),
    ]
