# Generated by Django 2.0.7 on 2018-07-13 20:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_remove_student_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='registered_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата і час реєстрації'),
            preserve_default=False,
        ),
    ]
