# Generated by Django 2.0.7 on 2018-07-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_student_registered_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.IntegerField(choices=[(0, 'Вільний'), (1, 'В процесі'), (2, 'Проголосував')], default=0, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='student',
            name='status_update_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Час останнього оновлення'),
        ),
    ]
