# Generated by Django 2.1 on 2018-09-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_add_trigram_extension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='status_update_time',
        ),
        migrations.AddField(
            model_name='student',
            name='status_update_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Час останнього оновлення'),
        ),
    ]
