# Generated by Django 2.1 on 2018-09-30 02:09

from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20180929_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='student.Specialty', verbose_name='Спеціальність'),
        ),
        migrations.AlterField(
            model_name='student',
            name='ticket_number',
            field=models.IntegerField(db_index=True, unique=True, validators=[student.models.validate_student_ticket_number], verbose_name='Номер студентського квитка'),
        ),
    ]
